pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: payment-service-build
                          connectorRef: account.bootcampgkecluster
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                spec:
                                    runOnlySelectedTests: true
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "2"
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    preCommand: cd payment-service
                                    packages: com.nikp
                                    language: Java
                                    image: nikpap/mvn-openjdk-8:harness
                                    connectorRef: account.bootcampdockerhub
                                    buildTool: Maven
                                    args: test
                                name: runTestsWithIntelligence
                                identifier: runTestsWithIntelligence
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    connectorRef: account.bootcampdockerhub
                                    image: nikpap/mvn-openjdk-8:harness
                                    command: |-
                                        cd payment-service
                                        mvn -Dmaven.test.skip=true clean install -X
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: pushToDockerHub
                                identifier: pushToDockerHub
                                spec:
                                    connectorRef: account.bootcampdockerhub
                                    repo: nikpap/payment-service
                                    tags:
                                        - LixCraft-latest
                                    dockerfile: /harness/payment-service/Dockerfile
                                    optimize: true
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                  cloneCodebase: true
              name: Build
              identifier: Build
    properties:
        ci:
            codebase:
                repoName: harness-cie-lab
                connectorRef: githubLixCraft
                build: <+input>
    projectIdentifier: handsoncieLixCraft
    orgIdentifier: default
    name: payment-service
    identifier: paymentservice
